### ISSUE TITLE
on date change, there is  can't read property error

### ISSUE THREAD

**Issue by romoy** [codefordc/dc-campaign-finance-watch#207]
On date change, the following error appear
`dashboardComponent.jsx:93 Uncaught (in promise) TypeError: Cannot read property 'campaigns' of undefined
    at t.value (https://codefordc.org/dc-campaign-finance-watch/dist/assets/app.js:52:10981)
    at https://codefordc.org/dc-campaign-finance-watch/dist/assets/app.js:52:13915
    at Array.map (native)
    at https://codefordc.org/dc-campaign-finance-watch/dist/assets/app.js:52:13466
    at Array.map (native)
    at t.value (https://codefordc.org/dc-campaign-finance-watch/dist/assets/app.js:52:13303)
    at d._renderValidatedComponentWithoutOwnerOrContext (https://codefordc.org/dc-campaign-finance-watch/dist/assets/app.js:76:10925)
    at d._renderValidatedComponent (https://codefordc.org/dc-campaign-finance-watch/dist/assets/app.js:76:11052)
    at d._updateRenderedComponent (https://codefordc.org/dc-campaign-finance-watch/dist/assets/app.js:76:10352)
    at d._performComponentUpdate (https://codefordc.org/dc-campaign-finance-watch/dist/assets/app.js:76:10153)
    at d.updateComponent (https://codefordc.org/dc-campaign-finance-watch/dist/assets/app.js:76:9431)
    at d.performUpdateIfNecessary (https://codefordc.org/dc-campaign-finance-watch/dist/assets/app.js:76:8758)
    at Object.performUpdateIfNecessary (https://codefordc.org/dc-campaign-finance-watch/dist/assets/app.js:19:29265)
    at s (https://codefordc.org/dc-campaign-finance-watch/dist/assets/app.js:12:10462)
    at r.perform (https://codefordc.org/dc-campaign-finance-watch/dist/assets/app.js:20:22262)
    at o.perform (https://codefordc.org/dc-campaign-finance-watch/dist/assets/app.js:20:22262)
value @ dashboardComponent.jsx:93
(anonymous) @ dashboardComponent.jsx:243
(anonymous) @ dashboardComponent.jsx:226
value @ dashboardComponent.jsx:221
_renderValidatedComponentWithoutOwnerOrContext @ ReactCompositeComponent.js:799
_renderValidatedComponent @ ReactCompositeComponent.js:822
_updateRenderedComponent @ ReactCompositeComponent.js:746
_performComponentUpdate @ ReactCompositeComponent.js:724
updateComponent @ ReactCompositeComponent.js:645
performUpdateIfNecessary @ ReactCompositeComponent.js:561
performUpdateIfNecessary @ ReactReconciler.js:157
s @ ReactUpdates.js:150
perform @ Transaction.js:140
perform @ Transaction.js:140
perform @ ReactUpdates.js:89
k @ ReactUpdates.js:172
closeAll @ Transaction.js:206
perform @ Transaction.js:153
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
u @ ReactUpdates.js:200
r @ ReactUpdateQueue.js:24
enqueueSetState @ ReactUpdateQueue.js:209
r.setState @ ReactComponent.js:63
(anonymous) @ dashboardComponent.jsx:195
dashboardComponent.jsx:93 Uncaught (in promise) TypeError: Cannot read property 'campaigns' of undefined`

## Expected Behavior

The listed campaigns update.

## Actual Behavior

The pervious campaign info remain.

## Steps to Reproduce

1. Visit https://codefordc.org/dc-campaign-finance-watch/dist/
2. Click the second date in the date drop down

## Your Environment

* Operating System
* Browser
* Desktop or mobile

**Comment by sdotson** [comment]
I could help troubleshoot this after figuring out local dev environment issue #208.

**Comment by romoy** [comment]
campaignData[campaignID] in the following line return undefined https://github.com/codefordc/dc-campaign-finance-watch/blob/develop/src/components/dashboard/dashboardComponent.jsx#L93

If you add a undefined value check, the score exist in the score card, info passed into https://github.com/codefordc/dc-campaign-finance-watch/blob/develop/src/components/dashboard/dashboardComponent.jsx#L235
